[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "VeriSnip"
version = "0.0.5"
authors = [
  { name="Pedro Nuno de Melo Antunes", email="pedroa@verisnip.com" },
]
description = "A framework to integrade scripting into hardware design."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "Apache-2.0"
license-files = ["LICENSE"]

[project.optional-dependencies]
test = ["pytest>=7"]


[project.urls]
Homepage = "https://github.com/VeriSnip/VeriSnip-Tool.git"
Issues = "https://github.com/VeriSnip/VeriSnip-Tool/issues"

[project.scripts]
vs_build = "VeriSnip.vs_build:main"
