"""Tests for VsSource._find_script: matching .vs includes to generator scripts."""

import os
import sys
import textwrap
from pathlib import Path

from VeriSnip.vs_build import VsBuilder


def test_exact_vs_name_matches_same_named_script(tmp_path: Path):
    """`include \"widget.vs\"` must resolve to widget.py with an empty suffix."""
    script = tmp_path / "widget.py"
    script.write_text("#!/usr/bin/env python3\n", encoding="utf-8")
    source = VsBuilder.VsSource("widget.vs")

    found, suffix = source._find_script([str(script)])

    assert found == str(script)
    assert suffix == ""


def test_prefixed_vs_matches_script_stem_without_vs_in_suffix(tmp_path: Path):
    """`include \"widget_logic.vs\"` matching widget.py passes suffix \"logic\"."""
    script = tmp_path / "widget.py"
    script.write_text("#!/usr/bin/env python3\n", encoding="utf-8")
    source = VsBuilder.VsSource("widget_logic.vs")

    found, suffix = source._find_script([str(script)])

    assert found == str(script)
    assert suffix == "logic"


def test_full_script_name_matches_include_stem(tmp_path: Path):
    """`include \"snippet_body.vs\"` must match snippet_body.py (exact stem)."""
    script = tmp_path / "snippet_body.py"
    script.write_text("#!/usr/bin/env python3\n", encoding="utf-8")
    source = VsBuilder.VsSource("snippet_body.vs")

    found, suffix = source._find_script([str(script)])

    assert found == str(script)
    assert suffix == ""


def test_longer_prefix_wins_over_shorter(tmp_path: Path):
    short = tmp_path / "io.py"
    long = tmp_path / "io_modules.py"
    short.write_text("#!/usr/bin/env python3\n", encoding="utf-8")
    long.write_text("#!/usr/bin/env python3\n", encoding="utf-8")
    source = VsBuilder.VsSource("io_modules.vs")

    found, suffix = source._find_script([str(short), str(long)])

    assert found == str(long)
    assert suffix == ""


GENERATOR_SCRIPT = textwrap.dedent(
    '''\
    #!/usr/bin/env python3
    """Writes <script_stem><suffix>.vs; empty suffix -> <script_stem>.vs."""
    import os
    import sys

    script_stem = os.path.splitext(os.path.basename(sys.argv[0]))[0]
    suffix = sys.argv[1] if len(sys.argv) > 1 else ""
    comment = sys.argv[2] if len(sys.argv) > 2 else ""
    out_name = f"{script_stem}_{suffix}.vs" if suffix else f"{script_stem}.vs"

    with open(out_name, "w", encoding="utf-8") as f:
        f.write(f"// generated by {script_stem} suffix={suffix!r} comment={comment}\\n")
        f.write("wire generated_ok;\\n")
    '''
)


def _run_resolve(tmp: Path) -> None:
    previous_cwd = os.getcwd()
    previous_argv = sys.argv[:]
    try:
        os.chdir(tmp)
        sys.argv = ["vs_build", "top"]
        builder = VsBuilder("top", "", [], [])
        builder.resolve_sources()
    finally:
        os.chdir(previous_cwd)
        sys.argv = previous_argv


def test_exact_named_include_generates_via_same_named_script(tmp_path: Path):
    """End-to-end: missing widget.vs is generated by widget.py (exact name match)."""
    (tmp_path / "top.v").write_text(
        textwrap.dedent(
            """\
            module top;
              `include "widget.vs" // MODE=exact
            endmodule
            """
        ),
        encoding="utf-8",
    )
    script = tmp_path / "widget.py"
    script.write_text(GENERATOR_SCRIPT, encoding="utf-8")
    script.chmod(0o755)

    _run_resolve(tmp_path)

    generated = tmp_path / "generated" / "widget.vs"
    assert generated.is_file(), f"expected generated snippet at {generated}"
    content = generated.read_text(encoding="utf-8")
    assert "suffix=''" in content
    assert "MODE=exact" in content
